<?php
/**
* Application settings.
* Make a copy of this file, fill in application values in that file.
* Rename the new file to settings.php
* Do not edit this file.
*/
	// echo "bla";
	$global_db_username		=	"dilshad";
	$global_db_password		=	"";
	$global_db_host			=	"localhost";
	$global_db_name			=	"dilshad";
	$global_db_port			=	"5432";
?>
